@Base_URL = https://localhost:7235

GET {{Base_URL}}/api/users
Accept: application/json
###

GET {{Base_URL}}/api/users/
Accept: application/json
###

GET {{Base_URL}}/api/users/by-email/?email=ziblimzulka.zz@gmail.com
Accept: application/json
###

POST {{Base_URL}}/api/users/register
Accept: application/json
Content-Type: application/json
{
  "email": "ziblimzulka.zz@gmail.com",
  "password": "Zz0$Zz6$",
  "phoneCountryCode": "+66",
  "phoneNumber": "0610718214",
  "role": "Customer"
}
###

POST {{Base_URL}}/api/users/signin
Accept: application/json
Content-Type: application/json
{
  "email": "ziblimzulka.zz@gmail.com",
  "password": "Zz0$Zz6$"
}
###

POST {{Base_URL}}/api/users/confirm-email
Accept: application/json
Content-Type: application/json
{
  "email": "ziblimzulka.zz@gmail.com"
}
###

POST {{Base_URL}}/api/users/change-password
Accept: application/json
Content-Type: application/json
{
  "Username": "ziblimzulka.zz@gmail.com",
  "OldPassword": "Zz0$Zz6$",
  "NewPassword": "Zz0$Zz6$"
}
###

DELETE {{Base_URL}}/api/users
Accept: application/json
###