# This workflow will build and test CraftConnect modules
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      homedrive:
        description: "The home drive on the machine."
        required: true
      loglevel:
        description: "Log level"
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      environment:
        description: "Environment to run tests against"
        type: environment
      tag:
        description: "Apply tag after a successful test run"
        required: true
        type: boolean

jobs:
  build:
    name: "Build CraftConnect"
    runs-on: ubuntu-latest
    steps:
    - name: "Workflow inputs"
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
          echo "Homedrive is: ${{ inputs.homedrive }}"
          echo "Log level is: ${{ inputs.loglevel }}"
          echo "Environment is: ${{ inputs.environment }}"
          echo "Tag source: ${{ inputs.tag }}"
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  test:
    name: "Test CraftConnect xUnit Project"
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Unit Tests
      run: dotnet test CraftConnect.Tests/CraftConnect.Tests.csproj --verbosity normal
